name: Promote Dev to Main

on:
  workflow_dispatch:

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Merge dev into main
        run: |
          git fetch origin
          git checkout main
          git merge origin/dev --no-ff -m "Promote dev to main"
          git push origin main
