name: Promote Dev to Main

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'Commit message for the merge'
        required: true
        default: 'Promote dev to main'

jobs:
  promote:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Merge dev into main
        run: |
          git fetch origin
          git checkout main
          git pull origin main
          if git merge origin/dev --no-ff -m "${{ github.event.inputs.commit_message }}"; then
            git push origin main
          else
            echo "Merge conflict detected"
            exit 1
          fi
